<a href="https://colab.research.google.com/github/Lustiyana/PrakPembelajaranMesin/blob/UTS/Template_UTS_Pembelajaran_Mesin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# UTS Pembelajaran Mesin

Nim, Nama, Kelas : LUSTIYANA 1197050061 D

# Topik Mini Riset

Mini riset ini mengenai prediksi churn pelanggan dengan menggunakan Artificial Neural Network

# Business Understanding 

**Latar Belakang**

Prediksi churn pelanggan adalah untuk mengukur mengapa pelanggan meninggalkan bisnis tertentu. Dalam kasus ini akan melihat churn pelanggan dalam bisnis telekomunikasi. Dimana diketahui bahwa Churn adalah salah satu masalah terbesar dalam industri telekomunikasi. Penelitian telah menunjukkan bahwa rata-rata tingkat churn bulanan di antara 4 operator nirkabel teratas di AS adalah 1,9% - 2%.

**Identifikasi Masalah**

Berdasarkan latar belakang masalah yang dapat diidentifikasi adalah bagaimana kita dapat memprediksi terjadinya churn sehingga dapat diatasi sedini mungkin.

**Metode/ Pendekatan Penyelesaian Masalah**

Metode penyelesaian masalah yang digunakan adalah dengan menggunakan Artificial Neural Network dan menggunakan, presisi, recall, dan f-1 score untuk mengukur kinerja model.

**Tujuan Teknis dan Kriteria Kesuksesan**

Memprediksi seberapa peningkatan jumlah churn khususnya di bidang telekomunikasi sehingga dapat diatasi lebih cepat dan tepat sasaran.

**Timeline Mini Riset**

membuat business understanding
mencari dataset
melakukan pengkodean

# Data Understanding

Disini dataset diambil dari Kaggle dengan 7043 row dan 21 column. Penjelasan dari setiap kolom sebagai berikut:

> ini rincian atribut/fitur/independent variable/kriteria:

1. CustomerId:- Represents customerId
2. gender:-jenis kelamin dari customer
3. SeniorCitizen:-merepresentasikan customer yang merupakan warga senior
4. Partner:-merepresentasikan pasangan customer
5. Dependents:-merepresentasikan tanggungan customer
6. Tenure:-merepresentasikan masa jabatan customer
7. PhoneService:-merepresentasikan layanan telepon customer
8. MultipleLines:-merepresentasikan layanan telepon lain milik customer
9. InternetService:-merepresentasikan layanan internet yang dipakai customer
10. OnlineSecurity:-merepresentasikan keamanan online customer
11. OnlineBackup:-merepresentasikan cadangan online customer
12. DeviceProtection:-merepresentasikan pengamanan perangkat customer
13. TectSupport:-merepresentasikan dukungan teknologi kepada customer
14. StreamingTV:-merepresentasikan kegiatan menonton TV customer
15. StreamingMovies:-merepresentasikan kegiatan menonton film customer
16. Contract:-merepresentasikan kontrak customer
17. PaperlessBilling:-merepresentasikan bukti bayar tidak berwujud
18. PaymentMethod:-merepresentasikan metode pembayaran customer
19. MonthlyCharges:-merepresentasikan biaya bulanan
20. TotalCharges:-merepresentasikan total biaya customer
21. Churn:-merepresentasikan apakah customer tersebut churn atau tidak

column 3, 4, 5, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 tidak dilibatkan karena uniq dan tidak berpengaruh

> ini variabel target/dependet variable/class/label

Exited:- Represents if a customer is going to exit the bank or not.

churn:-merepresentasikan jika customer meninggalkan bisnis telekomunikasi ini atau tidak

# Data Preparation

Membahas menggenai Load data, Pemilahan Data; Pembersihan Data; Konstruksi Data; Pelabelan Data; Integrasi Data (Catatan: Sampaikan proses penyiapan data yang dilakukan saja, sesuai kebutuhan studi kasus riset) berikut contohnya:

In [289]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

# load data

url = 'https://raw.githubusercontent.com/Lustiyana/PrakPembelajaranMesin/UTS/customer_churn.csv'
df = pd.read_csv(url, sep=',')

df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [236]:
df.info()

# pastikan gak ada yg null

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [237]:
# set independent variable/attribute/predictor/feature sampai kolom AGE
X = df.drop('Churn',axis='columns')
 
# set dependent variable/clas/target/label
y = df['Churn']

In [238]:
# ini jadinya X

X

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5

In [239]:
# yang ini Y nya

y

0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object

In [240]:
#Hapus colom customerID dari data frame
df.drop('customerID',axis='columns',inplace=True)

In [241]:
#melihat tipe data dari masing masing column
df.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [243]:
#lewati string apapun kecuali string TotalCharges dan mengabaikan parameter error
pd.to_numeric(df.TotalCharges,errors='coerce').isnull()

0       False
1       False
2       False
3       False
4       False
        ...
7038    False
7039    False
7040    False
7041    False
7042    False
Name: TotalCharges, Length: 7043, dtype: bool

In [244]:
df[pd.to_numeric(df.TotalCharges,errors='coerce').isnull()]

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,Male,0,No,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No
3331,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
3826,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
4380,Female,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
5218,Male,0,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
6670,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
6754,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

In [245]:
df.shape

(7043, 20)

In [246]:
df.iloc[488].TotalCharges

' '

In [247]:
df[df.TotalCharges!=' '].shape

(7032, 20)

In [248]:
df1 = df[df.TotalCharges!=' ']
df1.shape

(7032, 20)

In [249]:
df1.dtypes

gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [250]:
df1.TotalCharges = pd.to_numeric(df1.TotalCharges)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:5516: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [253]:
#mengklasifikasikan yang memiliki unique value
def print_unique_col_values(df):
       for column in df:
            if df[column].dtypes=='object':
                print(f'{column}: {df[column].unique()}')

In [254]:
#mengganti 'No internet service' dengan 'No' agar semua sama
df1.replace('No internet service','No',inplace=True)
df1.replace('No phone service','No',inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:5244: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,

In [255]:
#mengganti yes no column menjadi 1 dan 0
yes_no_columns = ['Partner','Dependents','PhoneService','MultipleLines','OnlineSecurity','OnlineBackup',
                  'DeviceProtection','TechSupport','StreamingTV','StreamingMovies','PaperlessBilling','Churn']
for col in yes_no_columns:
    df1[col].replace({'Yes': 1,'No': 0},inplace=True)
for col in df1:
    print(f'{col}: {df1[col].unique()}')

gender: ['Female' 'Male']
SeniorCitizen: [0 1]
Partner: [1 0]
Dependents: [0 1]
tenure: [ 1 34  2 45  8 22 10 28 62 13 16 58 49 25 69 52 71 21 12 30 47 72 17 27
  5 46 11 70 63 43 15 60 18 66  9  3 31 50 64 56  7 42 35 48 29 65 38 68
 32 55 37 36 41  6  4 33 67 23 57 61 14 20 53 40 59 24 44 19 54 51 26 39]
PhoneService: [0 1]
MultipleLines: [0 1]
InternetService: ['DSL' 'Fiber optic' 'No']
OnlineSecurity: [0 1]
OnlineBackup: [1 0]
DeviceProtection: [0 1]
TechSupport: [0 1]
StreamingTV: [0 1]
StreamingMovies: [0 1]
Contract: ['Month-to-month' 'One year' 'Two year']
PaperlessBilling: [1 0]
PaymentMethod: ['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
MonthlyCharges: [29.85 56.95 53.85 ... 63.1  44.2  78.7 ]
TotalCharges: [  29.85 1889.5   108.15 ...  346.45  306.6  6844.5 ]
Churn: [0 1]

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

In [256]:
df1['gender'].replace({'Female':1,'Male':0},inplace=True)
df2 = pd.get_dummies(data=df1, columns=['InternetService','Contract','PaymentMethod'])
cols_to_scale = ['tenure','MonthlyCharges','TotalCharges']

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df2[cols_to_scale] = scaler.fit_transform(df2[cols_to_scale])
for col in df2:
    print(f'{col}: {df2[col].unique()}')

gender: [1 0]
SeniorCitizen: [0 1]
Partner: [1 0]
Dependents: [0 1]
tenure: [0.         0.46478873 0.01408451 0.61971831 0.09859155 0.29577465
 0.12676056 0.38028169 0.85915493 0.16901408 0.21126761 0.8028169
 0.67605634 0.33802817 0.95774648 0.71830986 0.98591549 0.28169014
 0.15492958 0.4084507  0.64788732 1.         0.22535211 0.36619718
 0.05633803 0.63380282 0.14084507 0.97183099 0.87323944 0.5915493
 0.1971831  0.83098592 0.23943662 0.91549296 0.11267606 0.02816901
 0.42253521 0.69014085 0.88732394 0.77464789 0.08450704 0.57746479
 0.47887324 0.66197183 0.3943662  0.90140845 0.52112676 0.94366197
 0.43661972 0.76056338 0.50704225 0.49295775 0.56338028 0.07042254
 0.04225352 0.45070423 0.92957746 0.30985915 0.78873239 0.84507042
 0.18309859 0.26760563 0.73239437 0.54929577 0.81690141 0.32394366
 0.6056338  0.25352113 0.74647887 0.70422535 0.35211268 0.53521127]
PhoneService: [0 1]
MultipleLines: [0 1]
OnlineSecurity: [0 1]
OnlineBackup: [1 0]
DeviceProtection: [0 1]
TechSupport: [0 1]
StreamingTV: [0 1]
StreamingMovies: [0 1]
PaperlessBilling: [1 0]
MonthlyCharges: [0.11542289 0.38507463 0.35422886 ... 0.44626866 0.25820896 0.60149254]
TotalCharges: [0.0012751  0.21586661 0.01031041 ... 0.03780868 0.03321025 0.78764136]
Churn: [0 1]
InternetService_DSL: [1 0]
InternetService_Fiber optic: [0 1]
InternetService_No: [0 1]
Contract_Month-to-month: [1 0]
Contract_One year: [0 1]
Contract_Two year: [0 1]
PaymentMethod_Bank transfer (automatic): [0 1]
PaymentMethod_Credit card (automatic): [0 1]
PaymentMethod_Electronic check: [1 0]
PaymentMethod_Mailed check: [0 1]

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return self._update_inplace(result)

# Modeling

Membahas mengenai proses Fiting Model, set parameter-parameter dll.

In [257]:
#set independent variable
X = df2.drop('Churn',axis='columns')
#set dependent variable
y = df2['Churn']

#memisahkan data training dan testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=5)

In [282]:
#pemodelan dengan ANN
import tensorflow as tf
from tensorflow import keras


model = keras.Sequential([
    keras.layers.Dense(26, input_shape=(26,), activation='relu'),
    keras.layers.Dense(15, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

# opt = keras.optimizers.Adam(learning_rate=0.01)

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train, epochs=100)

Epoch 1/100
176/176 [==============================] - 2s 4ms/step - loss: 0.4888 - accuracy: 0.7575
Epoch 2/100
176/176 [==============================] - 1s 4ms/step - loss: 0.4311 - accuracy: 0.7911
Epoch 3/100
176/176 [==============================] - 1s 3ms/step - loss: 0.4228 - accuracy: 0.7973
Epoch 4/100
176/176 [==============================] - 1s 5ms/step - loss: 0.4188 - accuracy: 0.8023
Epoch 5/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4154 - accuracy: 0.8053
Epoch 6/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8050
Epoch 7/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4114 - accuracy: 0.8048
Epoch 8/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4100 - accuracy: 0.8044
Epoch 9/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8044
Epoch 10/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4069 - accuracy: 0.8069
Epoch 11/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8082
Epoch 12/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4047 - accuracy: 0.8068
Epoch 13/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4036 - accuracy: 0.8114
Epoch 14/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4033 - accuracy: 0.8116
Epoch 15/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4029 - accuracy: 0.8117
Epoch 16/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4009 - accuracy: 0.8107
Epoch 17/100
176/176 [==============================] - 0s 2ms/step - loss: 0.4002 - accuracy: 0.8108
Epoch 18/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3982 - accuracy: 0.8100
Epoch 19/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3979 - accuracy: 0.8135
Epoch 20/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3989 - accuracy: 0.8155
Epoch 21/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3955 - accuracy: 0.8172
Epoch 22/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3953 - accuracy: 0.8151
Epoch 23/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3958 - accuracy: 0.8130
Epoch 24/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3943 - accuracy: 0.8146
Epoch 25/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3932 - accuracy: 0.8149
Epoch 26/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3926 - accuracy: 0.8169
Epoch 27/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3914 - accuracy: 0.8176
Epoch 28/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3916 - accuracy: 0.8164
Epoch 29/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3899 - accuracy: 0.8176
Epoch 30/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3904 - accuracy: 0.8188
Epoch 31/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3886 - accuracy: 0.8148
Epoch 32/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3883 - accuracy: 0.8183
Epoch 33/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3878 - accuracy: 0.8188
Epoch 34/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3866 - accuracy: 0.8196
Epoch 35/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3857 - accuracy: 0.8201
Epoch 36/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3848 - accuracy: 0.8208
Epoch 37/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3848 - accuracy: 0.8188
Epoch 38/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3859 - accuracy: 0.8172
Epoch 39/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3823 - accuracy: 0.8217
Epoch 40/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3823 - accuracy: 0.8222
Epoch 41/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3818 - accuracy: 0.8233
Epoch 42/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3806 - accuracy: 0.8220
Epoch 43/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3806 - accuracy: 0.8219
Epoch 44/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3795 - accuracy: 0.8228
Epoch 45/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3795 - accuracy: 0.8203
Epoch 46/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3791 - accuracy: 0.8233
Epoch 47/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3770 - accuracy: 0.8215
Epoch 48/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3761 - accuracy: 0.8212
Epoch 49/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3760 - accuracy: 0.8229
Epoch 50/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3747 - accuracy: 0.8222
Epoch 51/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3745 - accuracy: 0.8244
Epoch 52/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3737 - accuracy: 0.8244
Epoch 53/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3731 - accuracy: 0.8238
Epoch 54/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3719 - accuracy: 0.8238
Epoch 55/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3721 - accuracy: 0.8265
Epoch 56/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3715 - accuracy: 0.8233
Epoch 57/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3710 - accuracy: 0.8245
Epoch 58/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3689 - accuracy: 0.8277
Epoch 59/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3688 - accuracy: 0.8258
Epoch 60/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3690 - accuracy: 0.8260
Epoch 61/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3671 - accuracy: 0.8315
Epoch 62/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3671 - accuracy: 0.8286
Epoch 63/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3672 - accuracy: 0.8279
Epoch 64/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3658 - accuracy: 0.8284
Epoch 65/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3665 - accuracy: 0.8272
Epoch 66/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3649 - accuracy: 0.8316
Epoch 67/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3638 - accuracy: 0.8304
Epoch 68/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3620 - accuracy: 0.8286
Epoch 69/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3617 - accuracy: 0.8299
Epoch 70/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3624 - accuracy: 0.8277
Epoch 71/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3621 - accuracy: 0.8313
Epoch 72/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3610 - accuracy: 0.8309
Epoch 73/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3617 - accuracy: 0.8302
Epoch 74/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3606 - accuracy: 0.8329
Epoch 75/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3593 - accuracy: 0.8300
Epoch 76/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3584 - accuracy: 0.8331
Epoch 77/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3590 - accuracy: 0.8279
Epoch 78/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3574 - accuracy: 0.8332
Epoch 79/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3569 - accuracy: 0.8347
Epoch 80/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3574 - accuracy: 0.8320
Epoch 81/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3567 - accuracy: 0.8336
Epoch 82/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3563 - accuracy: 0.8354
Epoch 83/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3554 - accuracy: 0.8320
Epoch 84/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3537 - accuracy: 0.8347
Epoch 85/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3532 - accuracy: 0.8348
Epoch 86/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3547 - accuracy: 0.8359
Epoch 87/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3549 - accuracy: 0.8350
Epoch 88/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3533 - accuracy: 0.8366
Epoch 89/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3523 - accuracy: 0.8370
Epoch 90/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3507 - accuracy: 0.8336
Epoch 91/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3528 - accuracy: 0.8318
Epoch 92/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3509 - accuracy: 0.8352
Epoch 93/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3502 - accuracy: 0.8361
Epoch 94/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3496 - accuracy: 0.8384
Epoch 95/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3494 - accuracy: 0.8370
Epoch 96/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3485 - accuracy: 0.8343
Epoch 97/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3486 - accuracy: 0.8338
Epoch 98/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3476 - accuracy: 0.8398
Epoch 99/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3475 - accuracy: 0.8389
Epoch 100/100
176/176 [==============================] - 0s 2ms/step - loss: 0.3473 - accuracy: 0.8382

# Evaluasi

Membahas mengenai hasil pengujian terhadap model.

In [283]:
# Menampilkan skor akurasi prediksi
model.evaluate(X_test, y_test)

44/44 [==============================] - 0s 2ms/step - loss: 0.5028 - accuracy: 0.7647

[0.5027608275413513, 0.764747679233551]

In [284]:
yp = model.predict(X_test)
yp[:5]

array([[2.7571493e-01],
       [3.1217682e-01],
       [3.1331182e-04],
       [7.5859529e-01],
       [3.5749051e-01]], dtype=float32)

In [285]:
y_pred = []
for element in yp:
    if element > 0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [286]:
y_pred[:10]

[0, 0, 0, 1, 0, 1, 0, 0, 0, 1]

In [287]:
y_test[:10]

2660    0
744     0
5579    1
64      1
3287    1
816     1
2670    0
5920    0
1023    0
6087    0
Name: Churn, dtype: int64

In [270]:
from sklearn.metrics import confusion_matrix , classification_report

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.81      0.91      0.85       999
           1       0.68      0.46      0.55       408

    accuracy                           0.78      1407
   macro avg       0.74      0.69      0.70      1407
weighted avg       0.77      0.78      0.77      1407

In [229]:
y_test.shape

(1407,)

In [230]:
#Akurasi yang didapatkan
round((862+229)/(862+229+137+179),2)

0.78

In [288]:
#Presisi untuk customer yang tidak churn
round(862/(862+179),2)

0.83

In [232]:
#Presisi untuk pelanggan yang benar-benar churn
round(229/(229+137),2)

0.63

In [290]:
#Recall untuk 0 class
round(862/(862+137),2)

0.86

In [291]:
round(229/(229+179),2)

0.56